name: Lint

on:
  push:
    branches:
      - main # Cambia esto al nombre de tu rama principal

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configura Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Cambia esto según tu versión de Node.js

    - name: Instala dependencias
      run: npm install

    - name: Instala eslint
      run: npm install eslint --save-dev

    - name: Configura eslint
      run: npx eslint --init

    - name: Ejecuta ESLint
      run: npx eslint .
