name: Análisis del código (Linting) con ESLint

on:
  push:
    branches:
      - main  

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Configuración de Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Instalación de Dependencias
      run: npm install
      working-directory: app-notas
    - name: Ejecución de ESLint
      run: npm run lint -- --fix
      working-directory: app-notas
   
      


