name: Configuración de Entorno

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Configuración de entorno
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Especifica la versión de Node.js que necesitas

    - name: Carga de variables de ambiente
      run: |
        # Define y exporta tus variables de ambiente aquí, si es necesario
        export MI_VARIABLE_SECRETA=secreto123
        # También puedes utilizar GitHub Secrets para almacenar variables de ambiente seguras
