name: Pruebas Unitarias

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Configuración de entorno
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Especifica la versión de Node.js que necesitas

    - name: Instalación de Dependencias
      run: npm install  # Asume que tienes un archivo package.json en tu repositorio

    - name: Ejecución de Pruebas Unitarias
      run: npm test 
